### PR TITLE
Update to support Luma 3DS v12.00

### PR DESCRIPTION
**Pull request by MegaloDawn**
Nimbus doesn't switch to pretendo and the friend manager is stuck on pretendo can't switch to nintendo

### CODE REVIEW

**Comment by MegaloDawn** [comment]
> Nimbus doesn't switch to pretendo and the friend manager is stuck on pretendo can't switch to nintendo

Idk how pull requsets work so its here.

**Comment by zaksabeast** [comment]
These commits look like they're from the Pretendo fork (https://github.com/PretendoNetwork/nimbus).  Were you meaning to post there?

**Comment by MegaloDawn** [comment]
> These commits look like they're from the Pretendo fork (https://github.com/PretendoNetwork/nimbus). Were you meaning to post there?

Yes but Idk how to put a pull request there and when i do it, it just goes here.

**Comment by zaksabeast** [comment]
I'm going to close this since it's not in the repo you want it to be.

It looks like you haven't forked the project, so when you made a pull request it defaulted to merge Pretendo's main branch into my repository's main branch.  You need to fork Pretendo's repository and push your changes to make a pull request.

Here are some instructions:
1. Fork Pretendo's repository
2. Commit any changes you want to make
3. Push your changes to your fork
4. Open a pull request to their repository

**Pull request closed without merging**
